
import streamlit as st 
import pandas as pd
import matplotlib.pyplot as plt


st.header('Shiv Shakti Stationary')
st.write('Inventory management system')

#df = pd.read_excel('1.xlsx')
sheet_url = 'https://docs.google.com/spreadsheets/d/1nrzGgh6Xf7w41WbMrnvJzv7t7BnhlRppwcpwTf-Z2vo/edit#gid=0'

url_1 = sheet_url.replace('/edit#gid=', '/export?format=csv&gid=')

df= pd.read_csv(url_1)



df.drop('S.No.', axis=1, inplace=True)

genre = st.radio(
     "What you have to do",
     ('Details for one Product', 'Products Stock less than 5', 'Bill System','Top Profit Product','Top Sales Product','Change in Database-add or remove or update'))

if genre == 'Details for one Product':
     option = st.selectbox(
     'Which Product details you want to know?',
     ("Polo Magetic Duster",
     "Natraj Pencil",
     "Natraj 621 Plasto Rubber",
     "Natraj Scale 15 cm",
     "Nataraj VIVID Ball Pens",
     "Apsara Non dust Regular Rubber",
     "Apsara Non dust Jumbo Rubber",
     "Apsara Long Point Sharpner",
     "Apsara 12 WAX CRAYONS COLOURS",
     "Apsara 16 WAX CRAYONS COLOURS",
     "Dom's Sharpner",
     "Dom's Pencil ",
     "ColorCandy Graphite Pencil (Long)",
     "Dom's Painting Brush (Pack of 5)",
     "Dom's Scale 30 cm ",
     "Dom's Wax Colours 24 Shades",
     "Dom's Wax colours 12 Shades",
     "Dom's Champions Kit",
     "Dom's Painting Kit",
     "Dom's Pencil Colours 12 pcs Small",
     "Dom's Pencil Colours 12 pcs Long",
     "Apsara Pencil ",
     "Infinity Gola Pencil ",
     "Gola Pencil 2.0 mm with Lead",
     "Cello Gola Pencil Lead - 0.7",
     "Cello Gola Pencil Lead - 0.9",
     "Flair X-Tra Strong Pencil Lead 2.0 ",
     "Music 555 Paper Pin",
     "Pentonic Ball Pen's ",
     "Pentonic Ball Pen's Refile",
     "Cello Jotdot Ball Pen",
     "Cello Aqua Gel Pen 0.6mm",
     "Cello Butterflow Ball Pen 0.7mm",
     "UNOMAX Turbo Glide Ball Pen",
     "UNOMAX UM5000 Ball Pen Refill",
     "UNOMAX NEXA Roller Pen-85",
     "UNOMAX Ball Pen's",
     "UNOMAX Gel Ball Pen's",
     "ELKOS RIO Black Gel Pen",
     "QUBA Glitter Gel Pen Colours",
     "Goldex Checkmate Ball Pen All Colours",
     "Flair Gel Pen Blue and Red",
     "Flair Zigma Gel Pen",
     "Goldex klassy Ball pen",
     "Goldex Cotton Doll Ball Pen",
     "Saino Softech Ball pen Regular Colours",
     "Saino PRIMO Ball Pen Colours",
     "UniBall Eye fine UB-157",
     "Reynolds Jetter AeroSoft Ball Pens",
     "Reynolds Jetter Classic Ball Pens",
     "Reynolds Waterproof Ink Ball Pens",
     "Reynolds Blue Cap Ball Pens",
     "LAOSHI Black Gel Pen",
     "Cello White Board Ink 15ml",
     "Kores White Board Marker",
     "Kores Permanent Marker",
     "Kores Multi Marker CD Pen",
     "Kores Highlighter",
     "Sunrise/Vasu Slate Pen (White)",
     "Five Colours Sticky Note",
     "INFINITY / MANGOOSE Sticky Notes Pads",
     "JB9 Sticky Note Pads",
     "Magnet for Children",
     "Yellow Sticky Pads Small",
     "Painting Brush (Pack of 10)",
     "Painting Brush (Pack of 4)",
     "Painting Brush (Single)",
     "ART Colour Painting Brush with tray",
     "Wedding Enevlop Cover",
     "White Enevlop Cover",
     "Libra Push Pins for Notice Board",
     "RealOne Push Pins for Notic Board",
     "Title low Dust White Choke",
     "Best Colour Choke -Dust Free",
     "Infinity / KORES Whitner Correction Pen",
     "Neelgagan Note Pads No. 33",
     "Classmate Note Book Size = 29.7 x 21 cm",
     "Classmate Note Book Size = 24 x 18 cm",
     "Classmate Graph Note Book Size 28 x 22 cm",
     "Classmate 3 in 1 Note Book - Size 24x18cm",
     "Vision Note Book Size = 210 x 297 mm",
     "Vision Note Book Size = 180 x 240 mm",
     "Sejal 144 pcs Note Book",
     "Libra 104 pages Note Book",
     "Luxor Graphic 05 Plus Pen",
     "Luxor Pilot Pen Blue Power Writing",
     "Luxor Converge Premium Note Book 21.6 x 27.9cm",
     "Luxor Converge Premium Note Book 17.6 x 25.0cm",
     "Luxor Converge Note Book 14.8 x 21.0 cm",
     "Luxor Converge Premium Note Book 14.0 x 21.6cm",
     "Luxor Converge Pocket Dairy 7.4 x 10.5 cm",
     "Dom's Packet Dairy 10.50 x7.40 cm",
     "Sundaram Premium Note Book 14 x 21.6 cm",
     "Vision Note Book (Maths) 160x190mm",
     "Sejal Note Book (Hindi) 160x190mm",
     "Sejal Note Book (English( 160x190mm",
     "Classmate Drawing Book Yellow 21x29.7cm",
     "Shape 19201 100 pages Pocket Note Pads",
     "U-Clip Box",
     "Classic U-Clip Box",
     "Stainless Scale 30 cm ",
     "Luxor Sketch Pen Colour 12 shades",
     "MR Fevicol 22.5 gm",
     "MR Fevicol 45 gm",
     "MR Fevicol 105 gm",
     "Fevi Stick 5 gm",
     "Fevi Stick 8 gm",
     "Fevi Stick 15 gm",
     "Fevi Stick 25 gm",
     "Fevi kwik",
     "Fevi Kwik Tube",
     "Softline Little Artist Colours Pen (Pack of 12 pcs)",
     "Exam Board",
     "kores Carbon Paper ",
     "Kores Carbon Paper (Single PCS)",
     "Kores Carbon Paper MultiCopy Gold",
     "B2B Xerox Paper GSM - 70",
     "B2B Xerox Paper GSM - 70 (New Arrival)",
     "K-One Xerox Paper GSM- 65",
     "AIRCON Damper Spenge Cup",
     "Kangaro Paper Punch DP-52",
     "Kangaro Stappler HD-10D",
     "Kangaro Stappler No.10",
     "Kangaro Paper Punch DP-500",
     "Kangaro Stappler Big HP-45",
     "Kangaro Stappler Mini-10",
     "Kangaro Stappler pin 24/6-1M - (20pcs)",
     "Kangaro stappler pin No.10-1M",
     "CITIZEN CALCULATOR - CT-512WT",
     "OREVA CALCULATOR - OR-512GT",
     "Premier Cutter",
     "Polo Snap off Cutter",
     "Brown Note Book Cover 5 mtr - 15",
     "Brown Note Book Cover 10 mtr - 15",
     "Garnet Polynet Cover 11 x 5",
     "Garnet Polynet Cover 12 x 10",
     "Garnet Polynet Cover 16 x 12",
     "SAGA Ring Binder Plastic Box file",
     "SVG Ring Binder Plastic Box file",
     "LAMINA Box file (Heard Board)",
     "Simple Box file",
     "Box file with spring",
     "Plastic A4 Paper Folder - Yellow / Red",
     "Plastic  A4 Paper Folder - Yellow/Transparents",
     "Plastic A4 Paper Folder - Checks Colours",
     "Apsara Designer's Kit ",
     "Little Master Colouring Book small S204",
     "Little Master Colouring Book Big L182",
     "Sheet Protector A4 Size 50 pcs",
     "Raj A4 Protector Sheet (50 PCS Pkt)",
     "Rangeela Tempera Water Colour",
     "Fevibond 8 ml",
     "Fevibond 25ml",
     "Kores Glue Stick 5 gm",
     "POLO Puff Double side Foam tape",
     "BIG 555 WONDER Form Tape",
     "POLO Handy Tape Dispenser",
     "7K Wonder/Premier Self Adhesive Tape",
     "7K Wonder Self Adhesive Tape",
     "7K Wonder Self Adhesive Tape",
     "7K Wonder Self Adhesive Tape - Brown",
     "IVY Grip Tape (Transparents Tape)",
     "M-Seal Phataphat (Blk) ",
     "M-Seal Tapelon tap 12x4mm",
     "Full Scape Paper 32.5 x 40.5 mm",
     "Vision Project Paper 225 x 290 mm",
     "Vision Project Paper 225 x 290 mm",
     "DuraCell Battery",
     "Eveready Battery",
     "HYW 9Volts Bettery",
     "KO Stick Ezey Gum 25ml",
     "KO Stick Ezey Gum 50ml",
     "Premium Mini Cutter",
     "Rangeela Creative clay",
     "Rangeela Moulding dough clay",
     "Infinity Scissors Stainless Steel",
     "MUNIX Scissor Model No. SL-1183",
     "Dakkash Stainless Hook",
     "Red tags for File",
     "Campas Box Assorted",
     "Vision ALB-821 Conference Pads",
     "Vision ALB-811 Conference Pads",
     "Red Border Sticker",
     "Cartoon Zipper Pouch",
     "VISION A128U Writing Pads",
     "SVS Cards Holder White",
     "Blue I.D. Card Belt",
     "PVC Electrical Ins. Tape (Black)",
     "Unique Chota Nawab colour Sketch Pen",
     "Camlin Postal Colours 6pcs Box",
     "Red Lions KeyChain Box",
     "Rangeela Moulding dough clay jar 150 gm",
     "Balaji Tissue Paper Napkin",
     "Umro Soft Tissue Paper Napkin 1 ply",
     "Paper Tray ",
     "Plastic Glass for Drinking",
     "Thermocol Tray ",
     "Balloon Rubber",
     "MAGNUS Binder Clips Small",
     "MAGNUS Binder Clips Big",
     "Select Stamp Pad Violet (88mm x 54mm)",
     "Faber-Castell Stamp Pad (110mm x 69mm)",
     "Faber-Castell Stamp Pad (88mm x 54mm)",
     "Faber-Castell CD Marker Black",
     "Faber-Castell Highlighter",
     "Faber-Castell Instrument Set (Plastic)",
     "Faber-Castell Poster Colour 12 pcs",
     "Stationery Design Ruler",
     "Premier Paper Clip No.3",
     "Premier Paper Clip No.4",
     "Camlin Rubber Stamp Ink 25ml",
     "BELL Nail Clipper (Plastic Coated)",
     "KABEE Nail Clipper Iron ",
     "Gas Lighter",
     "I.D. Card Key Chain for Hanging.",
     "Vision Register FA262 (Pages-288)",
     "Vision Register FA264 (Pages-144)",
     "Classtime Register (Pages-216)",
     "Snehraj 4 Quire Register",
     "Vision Exercise Note Book 192CB1",
     "LINC Signetta Blue Ball Pen",
     "LINC Ocean Wave Gel Pen Red",
     "LINC Executive Gel Pen",
     "LINC Signetta Blue Golden Ball Pen",
     "Saino Trio Ball pen ",
     "Nylon Rubber Band Small 13 gm",
     "Nylon Rubber Band Medicum 22 gm",
     "Kebica Pen Stand KBW-2105 - Wooden",
     "Music 555 Mesh Wire Round Pen Stand",
     "Music 555 Mesh Wire Square Pen Stand",
     "INFINITY A4 Sheet Protector INF-SP100",
     "Neelgagan Delivery Challan Book",
     "Jotter Refill for Pen",
     "GOG Voucher Book",
     "GOG Recepit Book 108 x 190 cm",
     "GOG Cash / Credit Memo Book - 140 x 220 mm",
     "Snehraj Cash / Credit Memo Estimate Book",
     "Snehraj Cash / Credit Memo Estimate Book",
     "Sakhee Account Book (Red) (Debit & Credit)",
     "Dhaval Attendance Register",
     "HENGLIANG GLUE GUN 40 WATTS - HL401",
     "NIYO GLUE GUN NY40 40 WATTS",
     "ARIHANT HOT MELT GLUE GUN STICK",
     "TRIO PLASTIC FILE FOLDER CODE EM12FHL",
     "SAGA EXPANDING FILE FOLDER CODE FE-444",
     "Chart Paper Ordinary",
     "Chart Paper Florocent Colour",
     "Name Label Sticker for Note Book",
     "Red Water Bottle",
     "Gift Packing Plastic Flower",
     "Gift Packing Sticker",
     "Gift Packing Colour Paper",
     "NANDI-G Writing Book",
     "Little Masters THREE IN ONE Book/70",
     "POOJA ALL IN ONE BOOK/120",
     "AVINASH Black Slate - 25 x 30 cm",
     "Slate white for Writing with Pen",
     "SWETA Slate with Wooden Frame ",
     "White Writing Board (2' x 3' fit)",
     "White Writing Board (1 1/2' x 2' fit)",
     "Notice Board (1 1/2' x 2' fit)",
     "Education Chart for Project Work",
     "Butter Paper for Cake"))

     #productDetails= input("Enter Product")

     Singlepd=df.loc[df['Name of Product.'] == option]

     st.dataframe(Singlepd)
     
elif genre == 'Products Stock less than 5': 
     st.write("Products stock less than 5")

     df.rename(columns = {'Stock Remain in Shop,':'stock_left'}, inplace = True)
     stleft=df[df.stock_left <5]

     st.dataframe(stleft)

elif genre == 'Bill System': 
     st.write("Bill System")

     SP='Selling Price'
     option1 = st.selectbox(
          'Item 1?',
          ("Polo Magetic Duster",
     "Natraj Pencil",
     "Natraj 621 Plasto Rubber",
     "Natraj Scale 15 cm",
     "Nataraj VIVID Ball Pens",
     "Apsara Non dust Regular Rubber",
     "Apsara Non dust Jumbo Rubber",
     "Apsara Long Point Sharpner",
     "Apsara 12 WAX CRAYONS COLOURS",
     "Apsara 16 WAX CRAYONS COLOURS",
     "Dom's Sharpner",
     "Dom's Pencil ",
     "ColorCandy Graphite Pencil (Long)",
     "Dom's Painting Brush (Pack of 5)",
     "Dom's Scale 30 cm ",
     "Dom's Wax Colours 24 Shades",
     "Dom's Wax colours 12 Shades",
     "Dom's Champions Kit",
     "Dom's Painting Kit",
     "Dom's Pencil Colours 12 pcs Small",
     "Dom's Pencil Colours 12 pcs Long",
     "Apsara Pencil ",
     "Infinity Gola Pencil ",
     "Gola Pencil 2.0 mm with Lead",
     "Cello Gola Pencil Lead - 0.7",
     "Cello Gola Pencil Lead - 0.9",
     "Flair X-Tra Strong Pencil Lead 2.0 ",
     "Music 555 Paper Pin",
     "Pentonic Ball Pen's ",
     "Pentonic Ball Pen's Refile",
     "Cello Jotdot Ball Pen",
     "Cello Aqua Gel Pen 0.6mm",
     "Cello Butterflow Ball Pen 0.7mm",
     "UNOMAX Turbo Glide Ball Pen",
     "UNOMAX UM5000 Ball Pen Refill",
     "UNOMAX NEXA Roller Pen-85",
     "UNOMAX Ball Pen's",
     "UNOMAX Gel Ball Pen's",
     "ELKOS RIO Black Gel Pen",
     "QUBA Glitter Gel Pen Colours",
     "Goldex Checkmate Ball Pen All Colours",
     "Flair Gel Pen Blue and Red",
     "Flair Zigma Gel Pen",
     "Goldex klassy Ball pen",
     "Goldex Cotton Doll Ball Pen",
     "Saino Softech Ball pen Regular Colours",
     "Saino PRIMO Ball Pen Colours",
     "UniBall Eye fine UB-157",
     "Reynolds Jetter AeroSoft Ball Pens",
     "Reynolds Jetter Classic Ball Pens",
     "Reynolds Waterproof Ink Ball Pens",
     "Reynolds Blue Cap Ball Pens",
     "LAOSHI Black Gel Pen",
     "Cello White Board Ink 15ml",
     "Kores White Board Marker",
     "Kores Permanent Marker",
     "Kores Multi Marker CD Pen",
     "Kores Highlighter",
     "Sunrise/Vasu Slate Pen (White)",
     "Five Colours Sticky Note",
     "INFINITY / MANGOOSE Sticky Notes Pads",
     "JB9 Sticky Note Pads",
     "Magnet for Children",
     "Yellow Sticky Pads Small",
     "Painting Brush (Pack of 10)",
     "Painting Brush (Pack of 4)",
     "Painting Brush (Single)",
     "ART Colour Painting Brush with tray",
     "Wedding Enevlop Cover",
     "White Enevlop Cover",
     "Libra Push Pins for Notice Board",
     "RealOne Push Pins for Notic Board",
     "Title low Dust White Choke",
     "Best Colour Choke -Dust Free",
     "Infinity / KORES Whitner Correction Pen",
     "Neelgagan Note Pads No. 33",
     "Classmate Note Book Size = 29.7 x 21 cm",
     "Classmate Note Book Size = 24 x 18 cm",
     "Classmate Graph Note Book Size 28 x 22 cm",
     "Classmate 3 in 1 Note Book - Size 24x18cm",
     "Vision Note Book Size = 210 x 297 mm",
     "Vision Note Book Size = 180 x 240 mm",
     "Sejal 144 pcs Note Book",
     "Libra 104 pages Note Book",
     "Luxor Graphic 05 Plus Pen",
     "Luxor Pilot Pen Blue Power Writing",
     "Luxor Converge Premium Note Book 21.6 x 27.9cm",
     "Luxor Converge Premium Note Book 17.6 x 25.0cm",
     "Luxor Converge Note Book 14.8 x 21.0 cm",
     "Luxor Converge Premium Note Book 14.0 x 21.6cm",
     "Luxor Converge Pocket Dairy 7.4 x 10.5 cm",
     "Dom's Packet Dairy 10.50 x7.40 cm",
     "Sundaram Premium Note Book 14 x 21.6 cm",
     "Vision Note Book (Maths) 160x190mm",
     "Sejal Note Book (Hindi) 160x190mm",
     "Sejal Note Book (English( 160x190mm",
     "Classmate Drawing Book Yellow 21x29.7cm",
     "Shape 19201 100 pages Pocket Note Pads",
     "U-Clip Box",
     "Classic U-Clip Box",
     "Stainless Scale 30 cm ",
     "Luxor Sketch Pen Colour 12 shades",
     "MR Fevicol 22.5 gm",
     "MR Fevicol 45 gm",
     "MR Fevicol 105 gm",
     "Fevi Stick 5 gm",
     "Fevi Stick 8 gm",
     "Fevi Stick 15 gm",
     "Fevi Stick 25 gm",
     "Fevi kwik",
     "Fevi Kwik Tube",
     "Softline Little Artist Colours Pen (Pack of 12 pcs)",
     "Exam Board",
     "kores Carbon Paper ",
     "Kores Carbon Paper (Single PCS)",
     "Kores Carbon Paper MultiCopy Gold",
     "B2B Xerox Paper GSM - 70",
     "B2B Xerox Paper GSM - 70 (New Arrival)",
     "K-One Xerox Paper GSM- 65",
     "AIRCON Damper Spenge Cup",
     "Kangaro Paper Punch DP-52",
     "Kangaro Stappler HD-10D",
     "Kangaro Stappler No.10",
     "Kangaro Paper Punch DP-500",
     "Kangaro Stappler Big HP-45",
     "Kangaro Stappler Mini-10",
     "Kangaro Stappler pin 24/6-1M - (20pcs)",
     "Kangaro stappler pin No.10-1M",
     "CITIZEN CALCULATOR - CT-512WT",
     "OREVA CALCULATOR - OR-512GT",
     "Premier Cutter",
     "Polo Snap off Cutter",
     "Brown Note Book Cover 5 mtr - 15",
     "Brown Note Book Cover 10 mtr - 15",
     "Garnet Polynet Cover 11 x 5",
     "Garnet Polynet Cover 12 x 10",
     "Garnet Polynet Cover 16 x 12",
     "SAGA Ring Binder Plastic Box file",
     "SVG Ring Binder Plastic Box file",
     "LAMINA Box file (Heard Board)",
     "Simple Box file",
     "Box file with spring",
     "Plastic A4 Paper Folder - Yellow / Red",
     "Plastic  A4 Paper Folder - Yellow/Transparents",
     "Plastic A4 Paper Folder - Checks Colours",
     "Apsara Designer's Kit ",
     "Little Master Colouring Book small S204",
     "Little Master Colouring Book Big L182",
     "Sheet Protector A4 Size 50 pcs",
     "Raj A4 Protector Sheet (50 PCS Pkt)",
     "Rangeela Tempera Water Colour",
     "Fevibond 8 ml",
     "Fevibond 25ml",
     "Kores Glue Stick 5 gm",
     "POLO Puff Double side Foam tape",
     "BIG 555 WONDER Form Tape",
     "POLO Handy Tape Dispenser",
     "7K Wonder/Premier Self Adhesive Tape",
     "7K Wonder Self Adhesive Tape",
     "7K Wonder Self Adhesive Tape",
     "7K Wonder Self Adhesive Tape - Brown",
     "IVY Grip Tape (Transparents Tape)",
     "M-Seal Phataphat (Blk) ",
     "M-Seal Tapelon tap 12x4mm",
     "Full Scape Paper 32.5 x 40.5 mm",
     "Vision Project Paper 225 x 290 mm",
     "Vision Project Paper 225 x 290 mm",
     "DuraCell Battery",
     "Eveready Battery",
     "HYW 9Volts Bettery",
     "KO Stick Ezey Gum 25ml",
     "KO Stick Ezey Gum 50ml",
     "Premium Mini Cutter",
     "Rangeela Creative clay",
     "Rangeela Moulding dough clay",
     "Infinity Scissors Stainless Steel",
     "MUNIX Scissor Model No. SL-1183",
     "Dakkash Stainless Hook",
     "Red tags for File",
     "Campas Box Assorted",
     "Vision ALB-821 Conference Pads",
     "Vision ALB-811 Conference Pads",
     "Red Border Sticker",
     "Cartoon Zipper Pouch",
     "VISION A128U Writing Pads",
     "SVS Cards Holder White",
     "Blue I.D. Card Belt",
     "PVC Electrical Ins. Tape (Black)",
     "Unique Chota Nawab colour Sketch Pen",
     "Camlin Postal Colours 6pcs Box",
     "Red Lions KeyChain Box",
     "Rangeela Moulding dough clay jar 150 gm",
     "Balaji Tissue Paper Napkin",
     "Umro Soft Tissue Paper Napkin 1 ply",
     "Paper Tray ",
     "Plastic Glass for Drinking",
     "Thermocol Tray ",
     "Balloon Rubber",
     "MAGNUS Binder Clips Small",
     "MAGNUS Binder Clips Big",
     "Select Stamp Pad Violet (88mm x 54mm)",
     "Faber-Castell Stamp Pad (110mm x 69mm)",
     "Faber-Castell Stamp Pad (88mm x 54mm)",
     "Faber-Castell CD Marker Black",
     "Faber-Castell Highlighter",
     "Faber-Castell Instrument Set (Plastic)",
     "Faber-Castell Poster Colour 12 pcs",
     "Stationery Design Ruler",
     "Premier Paper Clip No.3",
     "Premier Paper Clip No.4",
     "Camlin Rubber Stamp Ink 25ml",
     "BELL Nail Clipper (Plastic Coated)",
     "KABEE Nail Clipper Iron ",
     "Gas Lighter",
     "I.D. Card Key Chain for Hanging.",
     "Vision Register FA262 (Pages-288)",
     "Vision Register FA264 (Pages-144)",
     "Classtime Register (Pages-216)",
     "Snehraj 4 Quire Register",
     "Vision Exercise Note Book 192CB1",
     "LINC Signetta Blue Ball Pen",
     "LINC Ocean Wave Gel Pen Red",
     "LINC Executive Gel Pen",
     "LINC Signetta Blue Golden Ball Pen",
     "Saino Trio Ball pen ",
     "Nylon Rubber Band Small 13 gm",
     "Nylon Rubber Band Medicum 22 gm",
     "Kebica Pen Stand KBW-2105 - Wooden",
     "Music 555 Mesh Wire Round Pen Stand",
     "Music 555 Mesh Wire Square Pen Stand",
     "INFINITY A4 Sheet Protector INF-SP100",
     "Neelgagan Delivery Challan Book",
     "Jotter Refill for Pen",
     "GOG Voucher Book",
     "GOG Recepit Book 108 x 190 cm",
     "GOG Cash / Credit Memo Book - 140 x 220 mm",
     "Snehraj Cash / Credit Memo Estimate Book",
     "Snehraj Cash / Credit Memo Estimate Book",
     "Sakhee Account Book (Red) (Debit & Credit)",
     "Dhaval Attendance Register",
     "HENGLIANG GLUE GUN 40 WATTS - HL401",
     "NIYO GLUE GUN NY40 40 WATTS",
     "ARIHANT HOT MELT GLUE GUN STICK",
     "TRIO PLASTIC FILE FOLDER CODE EM12FHL",
     "SAGA EXPANDING FILE FOLDER CODE FE-444",
     "Chart Paper Ordinary",
     "Chart Paper Florocent Colour",
     "Name Label Sticker for Note Book",
     "Red Water Bottle",
     "Gift Packing Plastic Flower",
     "Gift Packing Sticker",
     "Gift Packing Colour Paper",
     "NANDI-G Writing Book",
     "Little Masters THREE IN ONE Book/70",
     "POOJA ALL IN ONE BOOK/120",
     "AVINASH Black Slate - 25 x 30 cm",
     "Slate white for Writing with Pen",
     "SWETA Slate with Wooden Frame ",
     "White Writing Board (2' x 3' fit)",
     "White Writing Board (1 1/2' x 2' fit)",
     "Notice Board (1 1/2' x 2' fit)",
     "Education Chart for Project Work",
     "Butter Paper for Cake"))
     if option1=='None':
          option1=0
          quant1=0
     else:

          quant1 = st.slider('How much this product?', 0, 100,key="1")


     option2 = st.selectbox(
          'Item 2?',
          ("None","Polo Magetic Duster",
     "Natraj Pencil",
     "Natraj 621 Plasto Rubber",
     "Natraj Scale 15 cm",
     "Nataraj VIVID Ball Pens",
     "Apsara Non dust Regular Rubber",
     "Apsara Non dust Jumbo Rubber",
     "Apsara Long Point Sharpner",
     "Apsara 12 WAX CRAYONS COLOURS",
     "Apsara 16 WAX CRAYONS COLOURS",
     "Dom's Sharpner",
     "Dom's Pencil ",
     "ColorCandy Graphite Pencil (Long)",
     "Dom's Painting Brush (Pack of 5)",
     "Dom's Scale 30 cm ",
     "Dom's Wax Colours 24 Shades",
     "Dom's Wax colours 12 Shades",
     "Dom's Champions Kit",
     "Dom's Painting Kit",
     "Dom's Pencil Colours 12 pcs Small",
     "Dom's Pencil Colours 12 pcs Long",
     "Apsara Pencil ",
     "Infinity Gola Pencil ",
     "Gola Pencil 2.0 mm with Lead",
     "Cello Gola Pencil Lead - 0.7",
     "Cello Gola Pencil Lead - 0.9",
     "Flair X-Tra Strong Pencil Lead 2.0 ",
     "Music 555 Paper Pin",
     "Pentonic Ball Pen's ",
     "Pentonic Ball Pen's Refile",
     "Cello Jotdot Ball Pen",
     "Cello Aqua Gel Pen 0.6mm",
     "Cello Butterflow Ball Pen 0.7mm",
     "UNOMAX Turbo Glide Ball Pen",
     "UNOMAX UM5000 Ball Pen Refill",
     "UNOMAX NEXA Roller Pen-85",
     "UNOMAX Ball Pen's",
     "UNOMAX Gel Ball Pen's",
     "ELKOS RIO Black Gel Pen",
     "QUBA Glitter Gel Pen Colours",
     "Goldex Checkmate Ball Pen All Colours",
     "Flair Gel Pen Blue and Red",
     "Flair Zigma Gel Pen",
     "Goldex klassy Ball pen",
     "Goldex Cotton Doll Ball Pen",
     "Saino Softech Ball pen Regular Colours",
     "Saino PRIMO Ball Pen Colours",
     "UniBall Eye fine UB-157",
     "Reynolds Jetter AeroSoft Ball Pens",
     "Reynolds Jetter Classic Ball Pens",
     "Reynolds Waterproof Ink Ball Pens",
     "Reynolds Blue Cap Ball Pens",
     "LAOSHI Black Gel Pen",
     "Cello White Board Ink 15ml",
     "Kores White Board Marker",
     "Kores Permanent Marker",
     "Kores Multi Marker CD Pen",
     "Kores Highlighter",
     "Sunrise/Vasu Slate Pen (White)",
     "Five Colours Sticky Note",
     "INFINITY / MANGOOSE Sticky Notes Pads",
     "JB9 Sticky Note Pads",
     "Magnet for Children",
     "Yellow Sticky Pads Small",
     "Painting Brush (Pack of 10)",
     "Painting Brush (Pack of 4)",
     "Painting Brush (Single)",
     "ART Colour Painting Brush with tray",
     "Wedding Enevlop Cover",
     "White Enevlop Cover",
     "Libra Push Pins for Notice Board",
     "RealOne Push Pins for Notic Board",
     "Title low Dust White Choke",
     "Best Colour Choke -Dust Free",
     "Infinity / KORES Whitner Correction Pen",
     "Neelgagan Note Pads No. 33",
     "Classmate Note Book Size = 29.7 x 21 cm",
     "Classmate Note Book Size = 24 x 18 cm",
     "Classmate Graph Note Book Size 28 x 22 cm",
     "Classmate 3 in 1 Note Book - Size 24x18cm",
     "Vision Note Book Size = 210 x 297 mm",
     "Vision Note Book Size = 180 x 240 mm",
     "Sejal 144 pcs Note Book",
     "Libra 104 pages Note Book",
     "Luxor Graphic 05 Plus Pen",
     "Luxor Pilot Pen Blue Power Writing",
     "Luxor Converge Premium Note Book 21.6 x 27.9cm",
     "Luxor Converge Premium Note Book 17.6 x 25.0cm",
     "Luxor Converge Note Book 14.8 x 21.0 cm",
     "Luxor Converge Premium Note Book 14.0 x 21.6cm",
     "Luxor Converge Pocket Dairy 7.4 x 10.5 cm",
     "Dom's Packet Dairy 10.50 x7.40 cm",
     "Sundaram Premium Note Book 14 x 21.6 cm",
     "Vision Note Book (Maths) 160x190mm",
     "Sejal Note Book (Hindi) 160x190mm",
     "Sejal Note Book (English( 160x190mm",
     "Classmate Drawing Book Yellow 21x29.7cm",
     "Shape 19201 100 pages Pocket Note Pads",
     "U-Clip Box",
     "Classic U-Clip Box",
     "Stainless Scale 30 cm ",
     "Luxor Sketch Pen Colour 12 shades",
     "MR Fevicol 22.5 gm",
     "MR Fevicol 45 gm",
     "MR Fevicol 105 gm",
     "Fevi Stick 5 gm",
     "Fevi Stick 8 gm",
     "Fevi Stick 15 gm",
     "Fevi Stick 25 gm",
     "Fevi kwik",
     "Fevi Kwik Tube",
     "Softline Little Artist Colours Pen (Pack of 12 pcs)",
     "Exam Board",
     "kores Carbon Paper ",
     "Kores Carbon Paper (Single PCS)",
     "Kores Carbon Paper MultiCopy Gold",
     "B2B Xerox Paper GSM - 70",
     "B2B Xerox Paper GSM - 70 (New Arrival)",
     "K-One Xerox Paper GSM- 65",
     "AIRCON Damper Spenge Cup",
     "Kangaro Paper Punch DP-52",
     "Kangaro Stappler HD-10D",
     "Kangaro Stappler No.10",
     "Kangaro Paper Punch DP-500",
     "Kangaro Stappler Big HP-45",
     "Kangaro Stappler Mini-10",
     "Kangaro Stappler pin 24/6-1M - (20pcs)",
     "Kangaro stappler pin No.10-1M",
     "CITIZEN CALCULATOR - CT-512WT",
     "OREVA CALCULATOR - OR-512GT",
     "Premier Cutter",
     "Polo Snap off Cutter",
     "Brown Note Book Cover 5 mtr - 15",
     "Brown Note Book Cover 10 mtr - 15",
     "Garnet Polynet Cover 11 x 5",
     "Garnet Polynet Cover 12 x 10",
     "Garnet Polynet Cover 16 x 12",
     "SAGA Ring Binder Plastic Box file",
     "SVG Ring Binder Plastic Box file",
     "LAMINA Box file (Heard Board)",
     "Simple Box file",
     "Box file with spring",
     "Plastic A4 Paper Folder - Yellow / Red",
     "Plastic  A4 Paper Folder - Yellow/Transparents",
     "Plastic A4 Paper Folder - Checks Colours",
     "Apsara Designer's Kit ",
     "Little Master Colouring Book small S204",
     "Little Master Colouring Book Big L182",
     "Sheet Protector A4 Size 50 pcs",
     "Raj A4 Protector Sheet (50 PCS Pkt)",
     "Rangeela Tempera Water Colour",
     "Fevibond 8 ml",
     "Fevibond 25ml",
     "Kores Glue Stick 5 gm",
     "POLO Puff Double side Foam tape",
     "BIG 555 WONDER Form Tape",
     "POLO Handy Tape Dispenser",
     "7K Wonder/Premier Self Adhesive Tape",
     "7K Wonder Self Adhesive Tape",
     "7K Wonder Self Adhesive Tape",
     "7K Wonder Self Adhesive Tape - Brown",
     "IVY Grip Tape (Transparents Tape)",
     "M-Seal Phataphat (Blk) ",
     "M-Seal Tapelon tap 12x4mm",
     "Full Scape Paper 32.5 x 40.5 mm",
     "Vision Project Paper 225 x 290 mm",
     "Vision Project Paper 225 x 290 mm",
     "DuraCell Battery",
     "Eveready Battery",
     "HYW 9Volts Bettery",
     "KO Stick Ezey Gum 25ml",
     "KO Stick Ezey Gum 50ml",
     "Premium Mini Cutter",
     "Rangeela Creative clay",
     "Rangeela Moulding dough clay",
     "Infinity Scissors Stainless Steel",
     "MUNIX Scissor Model No. SL-1183",
     "Dakkash Stainless Hook",
     "Red tags for File",
     "Campas Box Assorted",
     "Vision ALB-821 Conference Pads",
     "Vision ALB-811 Conference Pads",
     "Red Border Sticker",
     "Cartoon Zipper Pouch",
     "VISION A128U Writing Pads",
     "SVS Cards Holder White",
     "Blue I.D. Card Belt",
     "PVC Electrical Ins. Tape (Black)",
     "Unique Chota Nawab colour Sketch Pen",
     "Camlin Postal Colours 6pcs Box",
     "Red Lions KeyChain Box",
     "Rangeela Moulding dough clay jar 150 gm",
     "Balaji Tissue Paper Napkin",
     "Umro Soft Tissue Paper Napkin 1 ply",
     "Paper Tray ",
     "Plastic Glass for Drinking",
     "Thermocol Tray ",
     "Balloon Rubber",
     "MAGNUS Binder Clips Small",
     "MAGNUS Binder Clips Big",
     "Select Stamp Pad Violet (88mm x 54mm)",
     "Faber-Castell Stamp Pad (110mm x 69mm)",
     "Faber-Castell Stamp Pad (88mm x 54mm)",
     "Faber-Castell CD Marker Black",
     "Faber-Castell Highlighter",
     "Faber-Castell Instrument Set (Plastic)",
     "Faber-Castell Poster Colour 12 pcs",
     "Stationery Design Ruler",
     "Premier Paper Clip No.3",
     "Premier Paper Clip No.4",
     "Camlin Rubber Stamp Ink 25ml",
     "BELL Nail Clipper (Plastic Coated)",
     "KABEE Nail Clipper Iron ",
     "Gas Lighter",
     "I.D. Card Key Chain for Hanging.",
     "Vision Register FA262 (Pages-288)",
     "Vision Register FA264 (Pages-144)",
     "Classtime Register (Pages-216)",
     "Snehraj 4 Quire Register",
     "Vision Exercise Note Book 192CB1",
     "LINC Signetta Blue Ball Pen",
     "LINC Ocean Wave Gel Pen Red",
     "LINC Executive Gel Pen",
     "LINC Signetta Blue Golden Ball Pen",
     "Saino Trio Ball pen ",
     "Nylon Rubber Band Small 13 gm",
     "Nylon Rubber Band Medicum 22 gm",
     "Kebica Pen Stand KBW-2105 - Wooden",
     "Music 555 Mesh Wire Round Pen Stand",
     "Music 555 Mesh Wire Square Pen Stand",
     "INFINITY A4 Sheet Protector INF-SP100",
     "Neelgagan Delivery Challan Book",
     "Jotter Refill for Pen",
     "GOG Voucher Book",
     "GOG Recepit Book 108 x 190 cm",
     "GOG Cash / Credit Memo Book - 140 x 220 mm",
     "Snehraj Cash / Credit Memo Estimate Book",
     "Snehraj Cash / Credit Memo Estimate Book",
     "Sakhee Account Book (Red) (Debit & Credit)",
     "Dhaval Attendance Register",
     "HENGLIANG GLUE GUN 40 WATTS - HL401",
     "NIYO GLUE GUN NY40 40 WATTS",
     "ARIHANT HOT MELT GLUE GUN STICK",
     "TRIO PLASTIC FILE FOLDER CODE EM12FHL",
     "SAGA EXPANDING FILE FOLDER CODE FE-444",
     "Chart Paper Ordinary",
     "Chart Paper Florocent Colour",
     "Name Label Sticker for Note Book",
     "Red Water Bottle",
     "Gift Packing Plastic Flower",
     "Gift Packing Sticker",
     "Gift Packing Colour Paper",
     "NANDI-G Writing Book",
     "Little Masters THREE IN ONE Book/70",
     "POOJA ALL IN ONE BOOK/120",
     "AVINASH Black Slate - 25 x 30 cm",
     "Slate white for Writing with Pen",
     "SWETA Slate with Wooden Frame ",
     "White Writing Board (2' x 3' fit)",
     "White Writing Board (1 1/2' x 2' fit)",
     "Notice Board (1 1/2' x 2' fit)",
     "Education Chart for Project Work",
     "Butter Paper for Cake"))
     if option2=='None':
          option2=0
          quant2=0
     else:
          quant2 = st.slider('How much this product?', 0, 100,key="2")

     option3 = st.selectbox(
          'Item 3?',
          ("None","Polo Magetic Duster",
     "Natraj Pencil",
     "Natraj 621 Plasto Rubber",
     "Natraj Scale 15 cm",
     "Nataraj VIVID Ball Pens",
     "Apsara Non dust Regular Rubber",
     "Apsara Non dust Jumbo Rubber",
     "Apsara Long Point Sharpner",
     "Apsara 12 WAX CRAYONS COLOURS",
     "Apsara 16 WAX CRAYONS COLOURS",
     "Dom's Sharpner",
     "Dom's Pencil ",
     "ColorCandy Graphite Pencil (Long)",
     "Dom's Painting Brush (Pack of 5)",
     "Dom's Scale 30 cm ",
     "Dom's Wax Colours 24 Shades",
     "Dom's Wax colours 12 Shades",
     "Dom's Champions Kit",
     "Dom's Painting Kit",
     "Dom's Pencil Colours 12 pcs Small",
     "Dom's Pencil Colours 12 pcs Long",
     "Apsara Pencil ",
     "Infinity Gola Pencil ",
     "Gola Pencil 2.0 mm with Lead",
     "Cello Gola Pencil Lead - 0.7",
     "Cello Gola Pencil Lead - 0.9",
     "Flair X-Tra Strong Pencil Lead 2.0 ",
     "Music 555 Paper Pin",
     "Pentonic Ball Pen's ",
     "Pentonic Ball Pen's Refile",
     "Cello Jotdot Ball Pen",
     "Cello Aqua Gel Pen 0.6mm",
     "Cello Butterflow Ball Pen 0.7mm",
     "UNOMAX Turbo Glide Ball Pen",
     "UNOMAX UM5000 Ball Pen Refill",
     "UNOMAX NEXA Roller Pen-85",
     "UNOMAX Ball Pen's",
     "UNOMAX Gel Ball Pen's",
     "ELKOS RIO Black Gel Pen",
     "QUBA Glitter Gel Pen Colours",
     "Goldex Checkmate Ball Pen All Colours",
     "Flair Gel Pen Blue and Red",
     "Flair Zigma Gel Pen",
     "Goldex klassy Ball pen",
     "Goldex Cotton Doll Ball Pen",
     "Saino Softech Ball pen Regular Colours",
     "Saino PRIMO Ball Pen Colours",
     "UniBall Eye fine UB-157",
     "Reynolds Jetter AeroSoft Ball Pens",
     "Reynolds Jetter Classic Ball Pens",
     "Reynolds Waterproof Ink Ball Pens",
     "Reynolds Blue Cap Ball Pens",
     "LAOSHI Black Gel Pen",
     "Cello White Board Ink 15ml",
     "Kores White Board Marker",
     "Kores Permanent Marker",
     "Kores Multi Marker CD Pen",
     "Kores Highlighter",
     "Sunrise/Vasu Slate Pen (White)",
     "Five Colours Sticky Note",
     "INFINITY / MANGOOSE Sticky Notes Pads",
     "JB9 Sticky Note Pads",
     "Magnet for Children",
     "Yellow Sticky Pads Small",
     "Painting Brush (Pack of 10)",
     "Painting Brush (Pack of 4)",
     "Painting Brush (Single)",
     "ART Colour Painting Brush with tray",
     "Wedding Enevlop Cover",
     "White Enevlop Cover",
     "Libra Push Pins for Notice Board",
     "RealOne Push Pins for Notic Board",
     "Title low Dust White Choke",
     "Best Colour Choke -Dust Free",
     "Infinity / KORES Whitner Correction Pen",
     "Neelgagan Note Pads No. 33",
     "Classmate Note Book Size = 29.7 x 21 cm",
     "Classmate Note Book Size = 24 x 18 cm",
     "Classmate Graph Note Book Size 28 x 22 cm",
     "Classmate 3 in 1 Note Book - Size 24x18cm",
     "Vision Note Book Size = 210 x 297 mm",
     "Vision Note Book Size = 180 x 240 mm",
     "Sejal 144 pcs Note Book",
     "Libra 104 pages Note Book",
     "Luxor Graphic 05 Plus Pen",
     "Luxor Pilot Pen Blue Power Writing",
     "Luxor Converge Premium Note Book 21.6 x 27.9cm",
     "Luxor Converge Premium Note Book 17.6 x 25.0cm",
     "Luxor Converge Note Book 14.8 x 21.0 cm",
     "Luxor Converge Premium Note Book 14.0 x 21.6cm",
     "Luxor Converge Pocket Dairy 7.4 x 10.5 cm",
     "Dom's Packet Dairy 10.50 x7.40 cm",
     "Sundaram Premium Note Book 14 x 21.6 cm",
     "Vision Note Book (Maths) 160x190mm",
     "Sejal Note Book (Hindi) 160x190mm",
     "Sejal Note Book (English( 160x190mm",
     "Classmate Drawing Book Yellow 21x29.7cm",
     "Shape 19201 100 pages Pocket Note Pads",
     "U-Clip Box",
     "Classic U-Clip Box",
     "Stainless Scale 30 cm ",
     "Luxor Sketch Pen Colour 12 shades",
     "MR Fevicol 22.5 gm",
     "MR Fevicol 45 gm",
     "MR Fevicol 105 gm",
     "Fevi Stick 5 gm",
     "Fevi Stick 8 gm",
     "Fevi Stick 15 gm",
     "Fevi Stick 25 gm",
     "Fevi kwik",
     "Fevi Kwik Tube",
     "Softline Little Artist Colours Pen (Pack of 12 pcs)",
     "Exam Board",
     "kores Carbon Paper ",
     "Kores Carbon Paper (Single PCS)",
     "Kores Carbon Paper MultiCopy Gold",
     "B2B Xerox Paper GSM - 70",
     "B2B Xerox Paper GSM - 70 (New Arrival)",
     "K-One Xerox Paper GSM- 65",
     "AIRCON Damper Spenge Cup",
     "Kangaro Paper Punch DP-52",
     "Kangaro Stappler HD-10D",
     "Kangaro Stappler No.10",
     "Kangaro Paper Punch DP-500",
     "Kangaro Stappler Big HP-45",
     "Kangaro Stappler Mini-10",
     "Kangaro Stappler pin 24/6-1M - (20pcs)",
     "Kangaro stappler pin No.10-1M",
     "CITIZEN CALCULATOR - CT-512WT",
     "OREVA CALCULATOR - OR-512GT",
     "Premier Cutter",
     "Polo Snap off Cutter",
     "Brown Note Book Cover 5 mtr - 15",
     "Brown Note Book Cover 10 mtr - 15",
     "Garnet Polynet Cover 11 x 5",
     "Garnet Polynet Cover 12 x 10",
     "Garnet Polynet Cover 16 x 12",
     "SAGA Ring Binder Plastic Box file",
     "SVG Ring Binder Plastic Box file",
     "LAMINA Box file (Heard Board)",
     "Simple Box file",
     "Box file with spring",
     "Plastic A4 Paper Folder - Yellow / Red",
     "Plastic  A4 Paper Folder - Yellow/Transparents",
     "Plastic A4 Paper Folder - Checks Colours",
     "Apsara Designer's Kit ",
     "Little Master Colouring Book small S204",
     "Little Master Colouring Book Big L182",
     "Sheet Protector A4 Size 50 pcs",
     "Raj A4 Protector Sheet (50 PCS Pkt)",
     "Rangeela Tempera Water Colour",
     "Fevibond 8 ml",
     "Fevibond 25ml",
     "Kores Glue Stick 5 gm",
     "POLO Puff Double side Foam tape",
     "BIG 555 WONDER Form Tape",
     "POLO Handy Tape Dispenser",
     "7K Wonder/Premier Self Adhesive Tape",
     "7K Wonder Self Adhesive Tape",
     "7K Wonder Self Adhesive Tape",
     "7K Wonder Self Adhesive Tape - Brown",
     "IVY Grip Tape (Transparents Tape)",
     "M-Seal Phataphat (Blk) ",
     "M-Seal Tapelon tap 12x4mm",
     "Full Scape Paper 32.5 x 40.5 mm",
     "Vision Project Paper 225 x 290 mm",
     "Vision Project Paper 225 x 290 mm",
     "DuraCell Battery",
     "Eveready Battery",
     "HYW 9Volts Bettery",
     "KO Stick Ezey Gum 25ml",
     "KO Stick Ezey Gum 50ml",
     "Premium Mini Cutter",
     "Rangeela Creative clay",
     "Rangeela Moulding dough clay",
     "Infinity Scissors Stainless Steel",
     "MUNIX Scissor Model No. SL-1183",
     "Dakkash Stainless Hook",
     "Red tags for File",
     "Campas Box Assorted",
     "Vision ALB-821 Conference Pads",
     "Vision ALB-811 Conference Pads",
     "Red Border Sticker",
     "Cartoon Zipper Pouch",
     "VISION A128U Writing Pads",
     "SVS Cards Holder White",
     "Blue I.D. Card Belt",
     "PVC Electrical Ins. Tape (Black)",
     "Unique Chota Nawab colour Sketch Pen",
     "Camlin Postal Colours 6pcs Box",
     "Red Lions KeyChain Box",
     "Rangeela Moulding dough clay jar 150 gm",
     "Balaji Tissue Paper Napkin",
     "Umro Soft Tissue Paper Napkin 1 ply",
     "Paper Tray ",
     "Plastic Glass for Drinking",
     "Thermocol Tray ",
     "Balloon Rubber",
     "MAGNUS Binder Clips Small",
     "MAGNUS Binder Clips Big",
     "Select Stamp Pad Violet (88mm x 54mm)",
     "Faber-Castell Stamp Pad (110mm x 69mm)",
     "Faber-Castell Stamp Pad (88mm x 54mm)",
     "Faber-Castell CD Marker Black",
     "Faber-Castell Highlighter",
     "Faber-Castell Instrument Set (Plastic)",
     "Faber-Castell Poster Colour 12 pcs",
     "Stationery Design Ruler",
     "Premier Paper Clip No.3",
     "Premier Paper Clip No.4",
     "Camlin Rubber Stamp Ink 25ml",
     "BELL Nail Clipper (Plastic Coated)",
     "KABEE Nail Clipper Iron ",
     "Gas Lighter",
     "I.D. Card Key Chain for Hanging.",
     "Vision Register FA262 (Pages-288)",
     "Vision Register FA264 (Pages-144)",
     "Classtime Register (Pages-216)",
     "Snehraj 4 Quire Register",
     "Vision Exercise Note Book 192CB1",
     "LINC Signetta Blue Ball Pen",
     "LINC Ocean Wave Gel Pen Red",
     "LINC Executive Gel Pen",
     "LINC Signetta Blue Golden Ball Pen",
     "Saino Trio Ball pen ",
     "Nylon Rubber Band Small 13 gm",
     "Nylon Rubber Band Medicum 22 gm",
     "Kebica Pen Stand KBW-2105 - Wooden",
     "Music 555 Mesh Wire Round Pen Stand",
     "Music 555 Mesh Wire Square Pen Stand",
     "INFINITY A4 Sheet Protector INF-SP100",
     "Neelgagan Delivery Challan Book",
     "Jotter Refill for Pen",
     "GOG Voucher Book",
     "GOG Recepit Book 108 x 190 cm",
     "GOG Cash / Credit Memo Book - 140 x 220 mm",
     "Snehraj Cash / Credit Memo Estimate Book",
     "Snehraj Cash / Credit Memo Estimate Book",
     "Sakhee Account Book (Red) (Debit & Credit)",
     "Dhaval Attendance Register",
     "HENGLIANG GLUE GUN 40 WATTS - HL401",
     "NIYO GLUE GUN NY40 40 WATTS",
     "ARIHANT HOT MELT GLUE GUN STICK",
     "TRIO PLASTIC FILE FOLDER CODE EM12FHL",
     "SAGA EXPANDING FILE FOLDER CODE FE-444",
     "Chart Paper Ordinary",
     "Chart Paper Florocent Colour",
     "Name Label Sticker for Note Book",
     "Red Water Bottle",
     "Gift Packing Plastic Flower",
     "Gift Packing Sticker",
     "Gift Packing Colour Paper",
     "NANDI-G Writing Book",
     "Little Masters THREE IN ONE Book/70",
     "POOJA ALL IN ONE BOOK/120",
     "AVINASH Black Slate - 25 x 30 cm",
     "Slate white for Writing with Pen",
     "SWETA Slate with Wooden Frame ",
     "White Writing Board (2' x 3' fit)",
     "White Writing Board (1 1/2' x 2' fit)",
     "Notice Board (1 1/2' x 2' fit)",
     "Education Chart for Project Work",
     "Butter Paper for Cake"))
     if option3=='None':
          option3=0
          quant3=0
     else:
          quant3 = st.slider('How much this product?', 0, 100,key="3")

     option4 = st.selectbox(
          'Item 4?',
          ("None","Polo Magetic Duster",
     "Natraj Pencil",
     "Natraj 621 Plasto Rubber",
     "Natraj Scale 15 cm",
     "Nataraj VIVID Ball Pens",
     "Apsara Non dust Regular Rubber",
     "Apsara Non dust Jumbo Rubber",
     "Apsara Long Point Sharpner",
     "Apsara 12 WAX CRAYONS COLOURS",
     "Apsara 16 WAX CRAYONS COLOURS",
     "Dom's Sharpner",
     "Dom's Pencil ",
     "ColorCandy Graphite Pencil (Long)",
     "Dom's Painting Brush (Pack of 5)",
     "Dom's Scale 30 cm ",
     "Dom's Wax Colours 24 Shades",
     "Dom's Wax colours 12 Shades",
     "Dom's Champions Kit",
     "Dom's Painting Kit",
     "Dom's Pencil Colours 12 pcs Small",
     "Dom's Pencil Colours 12 pcs Long",
     "Apsara Pencil ",
     "Infinity Gola Pencil ",
     "Gola Pencil 2.0 mm with Lead",
     "Cello Gola Pencil Lead - 0.7",
     "Cello Gola Pencil Lead - 0.9",
     "Flair X-Tra Strong Pencil Lead 2.0 ",
     "Music 555 Paper Pin",
     "Pentonic Ball Pen's ",
     "Pentonic Ball Pen's Refile",
     "Cello Jotdot Ball Pen",
     "Cello Aqua Gel Pen 0.6mm",
     "Cello Butterflow Ball Pen 0.7mm",
     "UNOMAX Turbo Glide Ball Pen",
     "UNOMAX UM5000 Ball Pen Refill",
     "UNOMAX NEXA Roller Pen-85",
     "UNOMAX Ball Pen's",
     "UNOMAX Gel Ball Pen's",
     "ELKOS RIO Black Gel Pen",
     "QUBA Glitter Gel Pen Colours",
     "Goldex Checkmate Ball Pen All Colours",
     "Flair Gel Pen Blue and Red",
     "Flair Zigma Gel Pen",
     "Goldex klassy Ball pen",
     "Goldex Cotton Doll Ball Pen",
     "Saino Softech Ball pen Regular Colours",
     "Saino PRIMO Ball Pen Colours",
     "UniBall Eye fine UB-157",
     "Reynolds Jetter AeroSoft Ball Pens",
     "Reynolds Jetter Classic Ball Pens",
     "Reynolds Waterproof Ink Ball Pens",
     "Reynolds Blue Cap Ball Pens",
     "LAOSHI Black Gel Pen",
     "Cello White Board Ink 15ml",
     "Kores White Board Marker",
     "Kores Permanent Marker",
     "Kores Multi Marker CD Pen",
     "Kores Highlighter",
     "Sunrise/Vasu Slate Pen (White)",
     "Five Colours Sticky Note",
     "INFINITY / MANGOOSE Sticky Notes Pads",
     "JB9 Sticky Note Pads",
     "Magnet for Children",
     "Yellow Sticky Pads Small",
     "Painting Brush (Pack of 10)",
     "Painting Brush (Pack of 4)",
     "Painting Brush (Single)",
     "ART Colour Painting Brush with tray",
     "Wedding Enevlop Cover",
     "White Enevlop Cover",
     "Libra Push Pins for Notice Board",
     "RealOne Push Pins for Notic Board",
     "Title low Dust White Choke",
     "Best Colour Choke -Dust Free",
     "Infinity / KORES Whitner Correction Pen",
     "Neelgagan Note Pads No. 33",
     "Classmate Note Book Size = 29.7 x 21 cm",
     "Classmate Note Book Size = 24 x 18 cm",
     "Classmate Graph Note Book Size 28 x 22 cm",
     "Classmate 3 in 1 Note Book - Size 24x18cm",
     "Vision Note Book Size = 210 x 297 mm",
     "Vision Note Book Size = 180 x 240 mm",
     "Sejal 144 pcs Note Book",
     "Libra 104 pages Note Book",
     "Luxor Graphic 05 Plus Pen",
     "Luxor Pilot Pen Blue Power Writing",
     "Luxor Converge Premium Note Book 21.6 x 27.9cm",
     "Luxor Converge Premium Note Book 17.6 x 25.0cm",
     "Luxor Converge Note Book 14.8 x 21.0 cm",
     "Luxor Converge Premium Note Book 14.0 x 21.6cm",
     "Luxor Converge Pocket Dairy 7.4 x 10.5 cm",
     "Dom's Packet Dairy 10.50 x7.40 cm",
     "Sundaram Premium Note Book 14 x 21.6 cm",
     "Vision Note Book (Maths) 160x190mm",
     "Sejal Note Book (Hindi) 160x190mm",
     "Sejal Note Book (English( 160x190mm",
     "Classmate Drawing Book Yellow 21x29.7cm",
     "Shape 19201 100 pages Pocket Note Pads",
     "U-Clip Box",
     "Classic U-Clip Box",
     "Stainless Scale 30 cm ",
     "Luxor Sketch Pen Colour 12 shades",
     "MR Fevicol 22.5 gm",
     "MR Fevicol 45 gm",
     "MR Fevicol 105 gm",
     "Fevi Stick 5 gm",
     "Fevi Stick 8 gm",
     "Fevi Stick 15 gm",
     "Fevi Stick 25 gm",
     "Fevi kwik",
     "Fevi Kwik Tube",
     "Softline Little Artist Colours Pen (Pack of 12 pcs)",
     "Exam Board",
     "kores Carbon Paper ",
     "Kores Carbon Paper (Single PCS)",
     "Kores Carbon Paper MultiCopy Gold",
     "B2B Xerox Paper GSM - 70",
     "B2B Xerox Paper GSM - 70 (New Arrival)",
     "K-One Xerox Paper GSM- 65",
     "AIRCON Damper Spenge Cup",
     "Kangaro Paper Punch DP-52",
     "Kangaro Stappler HD-10D",
     "Kangaro Stappler No.10",
     "Kangaro Paper Punch DP-500",
     "Kangaro Stappler Big HP-45",
     "Kangaro Stappler Mini-10",
     "Kangaro Stappler pin 24/6-1M - (20pcs)",
     "Kangaro stappler pin No.10-1M",
     "CITIZEN CALCULATOR - CT-512WT",
     "OREVA CALCULATOR - OR-512GT",
     "Premier Cutter",
     "Polo Snap off Cutter",
     "Brown Note Book Cover 5 mtr - 15",
     "Brown Note Book Cover 10 mtr - 15",
     "Garnet Polynet Cover 11 x 5",
     "Garnet Polynet Cover 12 x 10",
     "Garnet Polynet Cover 16 x 12",
     "SAGA Ring Binder Plastic Box file",
     "SVG Ring Binder Plastic Box file",
     "LAMINA Box file (Heard Board)",
     "Simple Box file",
     "Box file with spring",
     "Plastic A4 Paper Folder - Yellow / Red",
     "Plastic  A4 Paper Folder - Yellow/Transparents",
     "Plastic A4 Paper Folder - Checks Colours",
     "Apsara Designer's Kit ",
     "Little Master Colouring Book small S204",
     "Little Master Colouring Book Big L182",
     "Sheet Protector A4 Size 50 pcs",
     "Raj A4 Protector Sheet (50 PCS Pkt)",
     "Rangeela Tempera Water Colour",
     "Fevibond 8 ml",
     "Fevibond 25ml",
     "Kores Glue Stick 5 gm",
     "POLO Puff Double side Foam tape",
     "BIG 555 WONDER Form Tape",
     "POLO Handy Tape Dispenser",
     "7K Wonder/Premier Self Adhesive Tape",
     "7K Wonder Self Adhesive Tape",
     "7K Wonder Self Adhesive Tape",
     "7K Wonder Self Adhesive Tape - Brown",
     "IVY Grip Tape (Transparents Tape)",
     "M-Seal Phataphat (Blk) ",
     "M-Seal Tapelon tap 12x4mm",
     "Full Scape Paper 32.5 x 40.5 mm",
     "Vision Project Paper 225 x 290 mm",
     "Vision Project Paper 225 x 290 mm",
     "DuraCell Battery",
     "Eveready Battery",
     "HYW 9Volts Bettery",
     "KO Stick Ezey Gum 25ml",
     "KO Stick Ezey Gum 50ml",
     "Premium Mini Cutter",
     "Rangeela Creative clay",
     "Rangeela Moulding dough clay",
     "Infinity Scissors Stainless Steel",
     "MUNIX Scissor Model No. SL-1183",
     "Dakkash Stainless Hook",
     "Red tags for File",
     "Campas Box Assorted",
     "Vision ALB-821 Conference Pads",
     "Vision ALB-811 Conference Pads",
     "Red Border Sticker",
     "Cartoon Zipper Pouch",
     "VISION A128U Writing Pads",
     "SVS Cards Holder White",
     "Blue I.D. Card Belt",
     "PVC Electrical Ins. Tape (Black)",
     "Unique Chota Nawab colour Sketch Pen",
     "Camlin Postal Colours 6pcs Box",
     "Red Lions KeyChain Box",
     "Rangeela Moulding dough clay jar 150 gm",
     "Balaji Tissue Paper Napkin",
     "Umro Soft Tissue Paper Napkin 1 ply",
     "Paper Tray ",
     "Plastic Glass for Drinking",
     "Thermocol Tray ",
     "Balloon Rubber",
     "MAGNUS Binder Clips Small",
     "MAGNUS Binder Clips Big",
     "Select Stamp Pad Violet (88mm x 54mm)",
     "Faber-Castell Stamp Pad (110mm x 69mm)",
     "Faber-Castell Stamp Pad (88mm x 54mm)",
     "Faber-Castell CD Marker Black",
     "Faber-Castell Highlighter",
     "Faber-Castell Instrument Set (Plastic)",
     "Faber-Castell Poster Colour 12 pcs",
     "Stationery Design Ruler",
     "Premier Paper Clip No.3",
     "Premier Paper Clip No.4",
     "Camlin Rubber Stamp Ink 25ml",
     "BELL Nail Clipper (Plastic Coated)",
     "KABEE Nail Clipper Iron ",
     "Gas Lighter",
     "I.D. Card Key Chain for Hanging.",
     "Vision Register FA262 (Pages-288)",
     "Vision Register FA264 (Pages-144)",
     "Classtime Register (Pages-216)",
     "Snehraj 4 Quire Register",
     "Vision Exercise Note Book 192CB1",
     "LINC Signetta Blue Ball Pen",
     "LINC Ocean Wave Gel Pen Red",
     "LINC Executive Gel Pen",
     "LINC Signetta Blue Golden Ball Pen",
     "Saino Trio Ball pen ",
     "Nylon Rubber Band Small 13 gm",
     "Nylon Rubber Band Medicum 22 gm",
     "Kebica Pen Stand KBW-2105 - Wooden",
     "Music 555 Mesh Wire Round Pen Stand",
     "Music 555 Mesh Wire Square Pen Stand",
     "INFINITY A4 Sheet Protector INF-SP100",
     "Neelgagan Delivery Challan Book",
     "Jotter Refill for Pen",
     "GOG Voucher Book",
     "GOG Recepit Book 108 x 190 cm",
     "GOG Cash / Credit Memo Book - 140 x 220 mm",
     "Snehraj Cash / Credit Memo Estimate Book",
     "Snehraj Cash / Credit Memo Estimate Book",
     "Sakhee Account Book (Red) (Debit & Credit)",
     "Dhaval Attendance Register",
     "HENGLIANG GLUE GUN 40 WATTS - HL401",
     "NIYO GLUE GUN NY40 40 WATTS",
     "ARIHANT HOT MELT GLUE GUN STICK",
     "TRIO PLASTIC FILE FOLDER CODE EM12FHL",
     "SAGA EXPANDING FILE FOLDER CODE FE-444",
     "Chart Paper Ordinary",
     "Chart Paper Florocent Colour",
     "Name Label Sticker for Note Book",
     "Red Water Bottle",
     "Gift Packing Plastic Flower",
     "Gift Packing Sticker",
     "Gift Packing Colour Paper",
     "NANDI-G Writing Book",
     "Little Masters THREE IN ONE Book/70",
     "POOJA ALL IN ONE BOOK/120",
     "AVINASH Black Slate - 25 x 30 cm",
     "Slate white for Writing with Pen",
     "SWETA Slate with Wooden Frame ",
     "White Writing Board (2' x 3' fit)",
     "White Writing Board (1 1/2' x 2' fit)",
     "Notice Board (1 1/2' x 2' fit)",
     "Education Chart for Project Work",
     "Butter Paper for Cake"))
     if option4=='None':
          option4=0
          quant4=0
     else:
          quant4 = st.slider('How much this product?', 0, 100,key="4")

     option5 = st.selectbox(
          'Item 5?',
          ("None","Polo Magetic Duster",
     "Natraj Pencil",
     "Natraj 621 Plasto Rubber",
     "Natraj Scale 15 cm",
     "Nataraj VIVID Ball Pens",
     "Apsara Non dust Regular Rubber",
     "Apsara Non dust Jumbo Rubber",
     "Apsara Long Point Sharpner",
     "Apsara 12 WAX CRAYONS COLOURS",
     "Apsara 16 WAX CRAYONS COLOURS",
     "Dom's Sharpner",
     "Dom's Pencil ",
     "ColorCandy Graphite Pencil (Long)",
     "Dom's Painting Brush (Pack of 5)",
     "Dom's Scale 30 cm ",
     "Dom's Wax Colours 24 Shades",
     "Dom's Wax colours 12 Shades",
     "Dom's Champions Kit",
     "Dom's Painting Kit",
     "Dom's Pencil Colours 12 pcs Small",
     "Dom's Pencil Colours 12 pcs Long",
     "Apsara Pencil ",
     "Infinity Gola Pencil ",
     "Gola Pencil 2.0 mm with Lead",
     "Cello Gola Pencil Lead - 0.7",
     "Cello Gola Pencil Lead - 0.9",
     "Flair X-Tra Strong Pencil Lead 2.0 ",
     "Music 555 Paper Pin",
     "Pentonic Ball Pen's ",
     "Pentonic Ball Pen's Refile",
     "Cello Jotdot Ball Pen",
     "Cello Aqua Gel Pen 0.6mm",
     "Cello Butterflow Ball Pen 0.7mm",
     "UNOMAX Turbo Glide Ball Pen",
     "UNOMAX UM5000 Ball Pen Refill",
     "UNOMAX NEXA Roller Pen-85",
     "UNOMAX Ball Pen's",
     "UNOMAX Gel Ball Pen's",
     "ELKOS RIO Black Gel Pen",
     "QUBA Glitter Gel Pen Colours",
     "Goldex Checkmate Ball Pen All Colours",
     "Flair Gel Pen Blue and Red",
     "Flair Zigma Gel Pen",
     "Goldex klassy Ball pen",
     "Goldex Cotton Doll Ball Pen",
     "Saino Softech Ball pen Regular Colours",
     "Saino PRIMO Ball Pen Colours",
     "UniBall Eye fine UB-157",
     "Reynolds Jetter AeroSoft Ball Pens",
     "Reynolds Jetter Classic Ball Pens",
     "Reynolds Waterproof Ink Ball Pens",
     "Reynolds Blue Cap Ball Pens",
     "LAOSHI Black Gel Pen",
     "Cello White Board Ink 15ml",
     "Kores White Board Marker",
     "Kores Permanent Marker",
     "Kores Multi Marker CD Pen",
     "Kores Highlighter",
     "Sunrise/Vasu Slate Pen (White)",
     "Five Colours Sticky Note",
     "INFINITY / MANGOOSE Sticky Notes Pads",
     "JB9 Sticky Note Pads",
     "Magnet for Children",
     "Yellow Sticky Pads Small",
     "Painting Brush (Pack of 10)",
     "Painting Brush (Pack of 4)",
     "Painting Brush (Single)",
     "ART Colour Painting Brush with tray",
     "Wedding Enevlop Cover",
     "White Enevlop Cover",
     "Libra Push Pins for Notice Board",
     "RealOne Push Pins for Notic Board",
     "Title low Dust White Choke",
     "Best Colour Choke -Dust Free",
     "Infinity / KORES Whitner Correction Pen",
     "Neelgagan Note Pads No. 33",
     "Classmate Note Book Size = 29.7 x 21 cm",
     "Classmate Note Book Size = 24 x 18 cm",
     "Classmate Graph Note Book Size 28 x 22 cm",
     "Classmate 3 in 1 Note Book - Size 24x18cm",
     "Vision Note Book Size = 210 x 297 mm",
     "Vision Note Book Size = 180 x 240 mm",
     "Sejal 144 pcs Note Book",
     "Libra 104 pages Note Book",
     "Luxor Graphic 05 Plus Pen",
     "Luxor Pilot Pen Blue Power Writing",
     "Luxor Converge Premium Note Book 21.6 x 27.9cm",
     "Luxor Converge Premium Note Book 17.6 x 25.0cm",
     "Luxor Converge Note Book 14.8 x 21.0 cm",
     "Luxor Converge Premium Note Book 14.0 x 21.6cm",
     "Luxor Converge Pocket Dairy 7.4 x 10.5 cm",
     "Dom's Packet Dairy 10.50 x7.40 cm",
     "Sundaram Premium Note Book 14 x 21.6 cm",
     "Vision Note Book (Maths) 160x190mm",
     "Sejal Note Book (Hindi) 160x190mm",
     "Sejal Note Book (English( 160x190mm",
     "Classmate Drawing Book Yellow 21x29.7cm",
     "Shape 19201 100 pages Pocket Note Pads",
     "U-Clip Box",
     "Classic U-Clip Box",
     "Stainless Scale 30 cm ",
     "Luxor Sketch Pen Colour 12 shades",
     "MR Fevicol 22.5 gm",
     "MR Fevicol 45 gm",
     "MR Fevicol 105 gm",
     "Fevi Stick 5 gm",
     "Fevi Stick 8 gm",
     "Fevi Stick 15 gm",
     "Fevi Stick 25 gm",
     "Fevi kwik",
     "Fevi Kwik Tube",
     "Softline Little Artist Colours Pen (Pack of 12 pcs)",
     "Exam Board",
     "kores Carbon Paper ",
     "Kores Carbon Paper (Single PCS)",
     "Kores Carbon Paper MultiCopy Gold",
     "B2B Xerox Paper GSM - 70",
     "B2B Xerox Paper GSM - 70 (New Arrival)",
     "K-One Xerox Paper GSM- 65",
     "AIRCON Damper Spenge Cup",
     "Kangaro Paper Punch DP-52",
     "Kangaro Stappler HD-10D",
     "Kangaro Stappler No.10",
     "Kangaro Paper Punch DP-500",
     "Kangaro Stappler Big HP-45",
     "Kangaro Stappler Mini-10",
     "Kangaro Stappler pin 24/6-1M - (20pcs)",
     "Kangaro stappler pin No.10-1M",
     "CITIZEN CALCULATOR - CT-512WT",
     "OREVA CALCULATOR - OR-512GT",
     "Premier Cutter",
     "Polo Snap off Cutter",
     "Brown Note Book Cover 5 mtr - 15",
     "Brown Note Book Cover 10 mtr - 15",
     "Garnet Polynet Cover 11 x 5",
     "Garnet Polynet Cover 12 x 10",
     "Garnet Polynet Cover 16 x 12",
     "SAGA Ring Binder Plastic Box file",
     "SVG Ring Binder Plastic Box file",
     "LAMINA Box file (Heard Board)",
     "Simple Box file",
     "Box file with spring",
     "Plastic A4 Paper Folder - Yellow / Red",
     "Plastic  A4 Paper Folder - Yellow/Transparents",
     "Plastic A4 Paper Folder - Checks Colours",
     "Apsara Designer's Kit ",
     "Little Master Colouring Book small S204",
     "Little Master Colouring Book Big L182",
     "Sheet Protector A4 Size 50 pcs",
     "Raj A4 Protector Sheet (50 PCS Pkt)",
     "Rangeela Tempera Water Colour",
     "Fevibond 8 ml",
     "Fevibond 25ml",
     "Kores Glue Stick 5 gm",
     "POLO Puff Double side Foam tape",
     "BIG 555 WONDER Form Tape",
     "POLO Handy Tape Dispenser",
     "7K Wonder/Premier Self Adhesive Tape",
     "7K Wonder Self Adhesive Tape",
     "7K Wonder Self Adhesive Tape",
     "7K Wonder Self Adhesive Tape - Brown",
     "IVY Grip Tape (Transparents Tape)",
     "M-Seal Phataphat (Blk) ",
     "M-Seal Tapelon tap 12x4mm",
     "Full Scape Paper 32.5 x 40.5 mm",
     "Vision Project Paper 225 x 290 mm",
     "Vision Project Paper 225 x 290 mm",
     "DuraCell Battery",
     "Eveready Battery",
     "HYW 9Volts Bettery",
     "KO Stick Ezey Gum 25ml",
     "KO Stick Ezey Gum 50ml",
     "Premium Mini Cutter",
     "Rangeela Creative clay",
     "Rangeela Moulding dough clay",
     "Infinity Scissors Stainless Steel",
     "MUNIX Scissor Model No. SL-1183",
     "Dakkash Stainless Hook",
     "Red tags for File",
     "Campas Box Assorted",
     "Vision ALB-821 Conference Pads",
     "Vision ALB-811 Conference Pads",
     "Red Border Sticker",
     "Cartoon Zipper Pouch",
     "VISION A128U Writing Pads",
     "SVS Cards Holder White",
     "Blue I.D. Card Belt",
     "PVC Electrical Ins. Tape (Black)",
     "Unique Chota Nawab colour Sketch Pen",
     "Camlin Postal Colours 6pcs Box",
     "Red Lions KeyChain Box",
     "Rangeela Moulding dough clay jar 150 gm",
     "Balaji Tissue Paper Napkin",
     "Umro Soft Tissue Paper Napkin 1 ply",
     "Paper Tray ",
     "Plastic Glass for Drinking",
     "Thermocol Tray ",
     "Balloon Rubber",
     "MAGNUS Binder Clips Small",
     "MAGNUS Binder Clips Big",
     "Select Stamp Pad Violet (88mm x 54mm)",
     "Faber-Castell Stamp Pad (110mm x 69mm)",
     "Faber-Castell Stamp Pad (88mm x 54mm)",
     "Faber-Castell CD Marker Black",
     "Faber-Castell Highlighter",
     "Faber-Castell Instrument Set (Plastic)",
     "Faber-Castell Poster Colour 12 pcs",
     "Stationery Design Ruler",
     "Premier Paper Clip No.3",
     "Premier Paper Clip No.4",
     "Camlin Rubber Stamp Ink 25ml",
     "BELL Nail Clipper (Plastic Coated)",
     "KABEE Nail Clipper Iron ",
     "Gas Lighter",
     "I.D. Card Key Chain for Hanging.",
     "Vision Register FA262 (Pages-288)",
     "Vision Register FA264 (Pages-144)",
     "Classtime Register (Pages-216)",
     "Snehraj 4 Quire Register",
     "Vision Exercise Note Book 192CB1",
     "LINC Signetta Blue Ball Pen",
     "LINC Ocean Wave Gel Pen Red",
     "LINC Executive Gel Pen",
     "LINC Signetta Blue Golden Ball Pen",
     "Saino Trio Ball pen ",
     "Nylon Rubber Band Small 13 gm",
     "Nylon Rubber Band Medicum 22 gm",
     "Kebica Pen Stand KBW-2105 - Wooden",
     "Music 555 Mesh Wire Round Pen Stand",
     "Music 555 Mesh Wire Square Pen Stand",
     "INFINITY A4 Sheet Protector INF-SP100",
     "Neelgagan Delivery Challan Book",
     "Jotter Refill for Pen",
     "GOG Voucher Book",
     "GOG Recepit Book 108 x 190 cm",
     "GOG Cash / Credit Memo Book - 140 x 220 mm",
     "Snehraj Cash / Credit Memo Estimate Book",
     "Snehraj Cash / Credit Memo Estimate Book",
     "Sakhee Account Book (Red) (Debit & Credit)",
     "Dhaval Attendance Register",
     "HENGLIANG GLUE GUN 40 WATTS - HL401",
     "NIYO GLUE GUN NY40 40 WATTS",
     "ARIHANT HOT MELT GLUE GUN STICK",
     "TRIO PLASTIC FILE FOLDER CODE EM12FHL",
     "SAGA EXPANDING FILE FOLDER CODE FE-444",
     "Chart Paper Ordinary",
     "Chart Paper Florocent Colour",
     "Name Label Sticker for Note Book",
     "Red Water Bottle",
     "Gift Packing Plastic Flower",
     "Gift Packing Sticker",
     "Gift Packing Colour Paper",
     "NANDI-G Writing Book",
     "Little Masters THREE IN ONE Book/70",
     "POOJA ALL IN ONE BOOK/120",
     "AVINASH Black Slate - 25 x 30 cm",
     "Slate white for Writing with Pen",
     "SWETA Slate with Wooden Frame ",
     "White Writing Board (2' x 3' fit)",
     "White Writing Board (1 1/2' x 2' fit)",
     "Notice Board (1 1/2' x 2' fit)",
     "Education Chart for Project Work",
     "Butter Paper for Cake"))
     if option5=='None':
          option5=0
          quant5=0
     else:
          quant5 = st.slider('How much this product?', 0, 100,key="5")

     st.write('Total Bill generated')

     df.set_index('Name of Product.', inplace=True)


     SP1=df[SP][option1]
     SP2=df[SP][option2]
     SP3=df[SP][option3]
     SP4=df[SP][option4]
     SP5=df[SP][option5]

     TSP1=SP1 * quant1
     TSP2=SP2 * quant2
     TSP3=SP3 * quant3
     TSP4=SP4 * quant4
     TSP5=SP5 * quant5

     Tbill= TSP1 + TSP2 + TSP3 + TSP4 + TSP5
     
     st.header(Tbill)

     

elif genre == 'Top Profit Product':
     df.set_index('Name of Product.', inplace=True)
     st.header('Top Profit Product')
     profit1 = st.slider('Slider to find', 0, 100,key="7")
     Top5_Profit=df['Profit'].nlargest(profit1)
     st.dataframe(Top5_Profit)



elif genre == 'Top Sales Product':  
     df.set_index('Name of Product.', inplace=True)
     st.header('Top Sales Product')
     sales1=st.slider('Slider to find', 0, 100,key="8")
     Top5_sales=df['Sale in PCS'].nlargest(sales1)
     st.dataframe(Top5_sales)

elif genre == 'Change in Database-add or remove or update':     
     st.header('For change in Database click down below')
     st.write("check out this [link](https://docs.google.com/spreadsheets/d/1nrzGgh6Xf7w41WbMrnvJzv7t7BnhlRppwcpwTf-Z2vo/edit#gid=0)")     


else:
     st.write("You didn't select comedy.")







